# class Model(Protocol):
#     """Protocol for language models."""
#
#     config: Any
#
#     def query(self, messages: list[dict[str, str]], **kwargs) -> dict: ...
#
#     def format_message(self, **kwargs) -> dict: ...
#
#     def format_observation_messages(
#         self, message: dict, outputs: list[dict], template_vars: dict | None = None
#     ) -> list[dict]: ...
#
#     def get_template_vars(self, **kwargs) -> dict[str, Any]: ...
#
#     def serialize(self) -> dict: ...
